{
 "title": "RAID Array",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/storage\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/storage\"})",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/storage" }
     ]
    }
   ]
  },
  {
   "title": "/mnt/disk1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/disk1\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/disk1\"})",
     "measurement": "disk",
     "query": "(sum(node_filesystem_size_bytes{mountpoint=\"/mnt/disk1\"}) - sum(node_filesystem_free_bytes{mountpoint=\"/mnt/storage\"}))/ sum(node_filesystem_size_bytes{mountpoint=\"/mnt/storage\"}) * 100",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/disk1" }
     ]
    }
   ]
  },
  {
   "title": "/mnt/disk2",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/disk2\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/disk2\"})",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/disk2" }
     ]
    }
   ]
  },
  {
   "title": "/mnt/disk3",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/disk3\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/disk3\"})",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/disk3" }
     ]
    }
   ]
  },
  {
   "title": "/mnt/disk4",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/disk4\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/disk4\"})",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/disk4" }
     ]
    }
   ]
  },
  {
   "title": "/mnt/disk5",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/disk5\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/disk5\"})",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/mnt/disk5" }
     ]
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/(disk.+|storage)\"}) by (mountpoint)",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"total\") AS \"total\", last(\"free\") AS \"free\", last(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" = 'cloyster' AND (\"path\" =~ /\\/mnt\\/(disk|storage)/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/disk*" }
     ]
    },
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=~\"/mnt/(disk.+|storage)\"}) by (mountpoint)"
    },
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/(disk.+|storage)\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/(disk.+|storage)\"})"
    }
   ]
  },
  {
   "title": "IO per/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "legendFormat": "{{ device }}",
     "measurement": "disk",
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE \"host\" = 'cloyster' AND (\"path\" = '/mnt/disk1' OR \"path\" = '/mnt/disk2' OR \"path\" = '/mnt/disk3' OR \"path\" = '/mnt/disk4' OR \"path\" = '/mnt/disk5') AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/disk1" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk2" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk3" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk4" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk5" }
     ]
    }
   ]
  },
  {
   "title": "Disk Temp",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "alias": "$tag_device",
     "expr": "smartmon_temperature_celsius_raw_value",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "legendFormat": "{{ disk }}",
     "measurement": "hddtemp",
     "query": "SELECT last(\"temp_c\") AS \"temp\" FROM \"smart_device\" WHERE (\"host\" = 'cloyster') AND $timeFilter GROUP BY \"device\"",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "temp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_path",
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=~\"/mnt/disk.+\"} / node_filesystem_size_bytes{mountpoint=~\"/mnt/disk.+\"})",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "legendFormat": "{{ mountpoint }}",
     "measurement": "disk",
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE \"host\" = 'cloyster' AND (\"path\" = '/mnt/disk1' OR \"path\" = '/mnt/disk2' OR \"path\" = '/mnt/disk3' OR \"path\" = '/mnt/disk4' OR \"path\" = '/mnt/disk5') AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/disk1" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk2" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk3" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk4" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/disk5" }
     ]
    }
   ]
  },
  {
   "title": "Disk Temp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "/dev/$tag_device",
     "expr": "smartmon_temperature_celsius_raw_value",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "legendFormat": "{{ disk }}",
     "measurement": "smart_device",
     "select": [
      [
       { "params": [ "temp_c" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "cloyster" }
     ]
    }
   ]
  },
  {
   "title": "Total Free Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/storage\"}",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/mnt/storage" }
     ]
    }
   ]
  }
 ]
}